global using System;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Simple.App.Services;
global using static Simple.App.Services.ServicesFuncs;
global using static Simple.Infrastructure.Integrations.IntegrationsFuncs;