global using System;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Simple.Domain.Integrations;
global using Simple.Infrastructure.Integrations;
global using Scheduling.JobScheduler;
global using static Simple.Domain.Integrations.IntegrationsFuncs;
global using static Simple.Infrastructure.Integrations.IntegrationsFuncs;