@pathBase = http://localhost:5500
@mongoPathBase = {{pathBase}}/mongo

# @name create_mongo_contact
POST {{mongoPathBase}}/contacts HTTP/1.1
content-type: application/json

{
  "contactName": "contact1",
  "contactEmail": "contact1@test.com"
}

###

@mongo_contact_location = {{create_mongo_contact.response.headers.Location}}

# @name add_mongo_phone_number
POST {{pathBase}}{{mongo_contact_location}}/phonenumbers HTTP/1.1
content-type: application/json

{
  "countryCode": 123,
  "number": 123456789,
  "numberType": 0
}

###

@mongo_phonenumber_location = {{add_mongo_phone_number.response.headers.Location}}

# @name delete_mongo_phone_number
DELETE {{pathBase}}{{mongo_phonenumber_location}} HTTP/1.1
content-type: application/json

{
  "countryCode": 123,
  "number": 123456789
}

###